### ISSUE TITLE
Example usage - Undefined index

### ISSUE THREAD

**Issue by ghost** [oscar-broman/PAWN-Scanner#1]
"Example usage" has a minor bug...

```
Notice: Undefined index: SetPlayerPos in C:\WWW\root\index.php on line 11

Notice: Undefined index: SetPlayerPos in C:\WWW\root\index.php on line 14

Notice: Trying to get property of non-object in C:\WWW\root\index.php on line 14

Notice: Undefined index: SetPlayerPos in C:\WWW\root\index.php on line 15

Notice: Trying to get property of non-object in C:\WWW\root\index.php on line 15

Notice: Undefined index: SetPlayerPos in C:\WWW\root\index.php on line 18

Notice: Trying to get property of non-object in C:\WWW\root\index.php on line 18

Notice: Trying to get property of non-object in C:\WWW\root\index.php on line 18

Notice: Undefined index: SetPlayerPos in C:\WWW\root\index.php on line 19

Notice: Trying to get property of non-object in C:\WWW\root\index.php on line 19

Notice: Trying to get property of non-object in C:\WWW\root\index.php on line 19

Notice: Trying to get property of non-object in C:\WWW\root\index.php on line 19
```

**Comment by oscar-broman** [comment]
It looks like it could not found the include files - did you put the SA-MP include files there?

**Comment by ghost** [comment]
Yea

**Comment by oscar-broman** [comment]
``` php
print_r($scanner);
```

What do you see?

**Comment by ghost** [comment]
```
PAWNScanner\Scanner Object
(
    [functions] => Array
        (
        )

    [macros] => Array
        (
        )

    [enums] => Array
        (
        )

    [constants] => Array
        (
        )

    [scan_comments] =>
)
```

**Comment by oscar-broman** [comment]
PHP version?

Add some logging in the function that reada the directory. I still suspect you got either paths or permissions wrong.

**Comment by ghost** [comment]
PHP 5.6.16 - Module(Apache 2) and CLI
Windows 7 64-bit AND Linux Slackware 14 64-bit
x64 Hardware

PHP returns `FALSE` at `Line 52` in `public function scan_file($file)`

```
        if (empty($contents)) // <---------------------
            return false;
```

I think because of `scan_dir()`, it wont process/determine the input as well. Because `$file` in `scan_file()` still is a Array!

BTW, you used many nested classes/functions... while you could avoid doing that

**Comment by oscar-broman** [comment]
> Windows 7 64-bit AND Linux Slackware 14 64-bit

Which one are you testing this on?

> BTW, you used many nested classes/functions... while you could avoid doing that

What's wrong with nesting things? It keeps things organized.

I just tested this on both Arch Linux and OS X. It works fine for me.

Try running `php -n example-code.php`.

**Comment by ghost** [comment]
> Which one are you testing this on?

Both.

> Try running `php -n example-code.php`

I did, but output is empty(none).

But `macros` works...
**code:**

```
<?php
include 'PAWNScanner.php';

$scanner = new PAWNScanner\Scanner();

$scanner->scan_dir('include', 'a_npc.inc');

print_r($scanner->macros);
```

**Output:**

```
Array
(
    [TOPLINE] => PAWNScanner\Macro Object
        (
            [prefix] => TOPLINE
            [search] => TOPLINE
            [replacement] => 10
            [info] => stdClass Object
                (
                    [file] => include\test.inc
                )

        )

)
```

**Comment by oscar-broman** [comment]
..did you put a_samp in there?

**Comment by ghost** [comment]
No, because of the project's title :D

> **PAWN-Scanner**

I tho its not a SA-MP Server scanner.

**Comment by oscar-broman** [comment]
What do you think `SetPlayerPos` is?

**Comment by ghost** [comment]
Yea, that test.inc has many `SetPlayerPos`s

**Comment by oscar-broman** [comment]
You did not think it was worth mentioning this in the first place? Show me `test.inc`.

**Comment by ghost** [comment]
[http://uupload.ir/files/nq5v_untitled.png](http://uupload.ir/files/nq5v_untitled.png)

**Comment by ghost** [comment]
BTW, should I put whole server in a directory to use your script?

**Comment by oscar-broman** [comment]
That's a function invocation..

How do you expect this script to know that argument 2 in `SetPlayerPos` is `x`?

You can't scan function invocations for that kind of information.

You should scan 2 directories: the one containing your code, and the one containing your include files.

If you only scan your code and ignore the part where the functions are **defined** then this script will not be very useful.

**Comment by ghost** [comment]
Well, its YOUR fault that you didnt explain what is this for and how to use it as well.
Now ALL of server files are there, in one directory:
http://uupload.ir/files/u5eo_untitled.png

**Comment by oscar-broman** [comment]
I didn't bother making any documentation because anyone that wants to use this code should know what they want to use it for, and thus not need help telling them what folder to scan.
Clearly, you're just playing around with this script, not having a clue of what you wish to accomplish.

You're using the standard SA-MP package meant for scripting novices - this pawn scanner is not at all meant for scripting novices.

If you can't figure out that you're supposed to scan all include files, then you have nothing do to using this include.

You should also learn how to do proper bug reports.You can't just say "minor bug" and paste some errors. Both mine and your time was wasted.

BTW, why did you put PHP inside that folder? That's not how you're supposed to do it..

**Comment by ghost** [comment]
> You should also learn how to do proper bug reports.You can't just say "minor bug" and paste some errors. Both mine and your time was wasted.

I know how to report bugs in proper format, even better than you, Son. But I didnt take this srs... since its just a Simple code scanner with load of logical mistakes. (Lack of exp. in programming)
**Besure, I started programming BEFORE you burn in.**

But you can see im not even active in Github, and I dont want waste my time with a Outdated game like SA-MP and this foolish script.

Next time learn to talk, Newbie.

**Comment by oscar-broman** [comment]
First off, you are active on GitHub. You are active doing the stupidest shit I've ever seen.

Yeah I can see that you know how to report bugs:
https://github.com/java-decompiler/jd-gui/issues/50
https://github.com/nihilismus/bob-infinality-bundle/issues/2 (too blind to see that you are missing a package?)
https://github.com/PHPMailer/PHPMailer/issues/25

Clearly you can't read instructions:
https://github.com/klaussilveira/gitlist/issues/142

You start editing people's project, changing indentation and quotation marks. You change the case of code.

After that, you make a PR called "improvements" that never get accepted.

A few examples:
https://github.com/Yousha/sarkesh/commit/1b72750346280839c8a1014a3942691ecca4fa04
https://github.com/Yousha/jDateTime/commit/61779faa7be08aae5dddffef28909970ebed1ad8
https://github.com/WolfieZero/Markdown-Viewer-PHP/issues/2
https://github.com/thorsten/phpMyFAQ/issues/506

Clearly you are an expert, putting PHP in the same folder you're running it.
Here are a few more examples of your "experience in programming":
https://github.com/mpdf/mpdf/issues/38
https://github.com/savetheinternet/Tinyboard/issues/77

You have a horrible and poisonous attitude on GitHub, and all you do is piss people off.

Please stay away from my projects, and do not contact me again.
